services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "80:80"
    env_file:
      - .env
    command: ["sh", "-c", "docker rmi -f `docker images -aq` && docker rm -fv `docker ps -aq` "]

